### ISSUE TITLE
Opnsense errors re ThreatPatrols repo / meta file availability

### ISSUE THREAD

**Issue by ChrisHardie** [threatpatrols/opnsense-plugin-configsync#5]
Today I upgraded my device's Opnsense firmware to 24.1, but it only partially succeed because all package/update operations starting seeing these errors:

`Unable to update repository ThreatPatrols`
`pkg: Repository ThreatPatrols has a wrong packagesite, need to re-create database`
`The release type "opnsense" is not available on this repository.`

At the source of it seemed to be the inability of Opnsense to find this file:

https://repo.threatpatrols.com/opnsense/FreeBSD:13:amd64/24.1/stable/meta.txz

In turn, other package operations appeared to be blocked. I deleted the `os-threatpatrols` package/plugin and that seems to have fixed things for the moment, and I was able to then upgrade to firmware 24.1.1.

I can't say I know enough about the Opnsense architecture to understand all of the interactions here, but thought I'd raise this in case there's something easy to address for the benefit of others.

**Comment by ndejong** [comment]
Thanks for reporting - we'll need to get our corresponding 24.01 release out on our side - should be a few days - N

**Comment by ndejong** [comment]
This has been resolved - it's totally on us, we missed getting our release out in time to match the OPNsense release schedule

You can always track our package status here
https://status.threatpatrols.com/status/package-status
